title: "Rajendramani Notes"
description: "Learning Machine - Public Knowledge Base"
theme: minima

collections:
  learnfrommistakes:
    output: true
    permalink: /learnfrommistakes/:name/

plugins:
  - jekyll-paginate-v2

pagination:
  per_page: 5
  title: ":title - page :num"
  permalink: "/learnfrommistakes/page:num/"
  enabled: true
